agent_params_loader:
   ros__parameters:
       sampling_time: 0.033
       runge_kutta_45: True
       ground_height: -0.1
       robot_control: True
       robot_name: "pioneer3at"
       laser_sensor_name: "laser"
       robot_radius: 0.3
       robot_mass: 35
       robot_goal_weight: 2.0
       robot_obstacle_weight: 10.0
       robot_social_weight: 15.0
       robot_velocity: 0.9
       robot_initial_orientation: -3.1416
       robot_waypoints: [-6.5,-0.0,6.5,0.0]
       robot_initial_position: [6.5,0.0]
       robot_ignore_obstacles: ["circular_workspace"]
       attach_cylinder_to_humans: True
       consider_robot: True
       agents: ["agent1","agent2","agent3","agent4","agent5"]
       agent1:
           waypoints: [-3.25,-5.6292,3.25,5.6292]
           initial_orientation: -2.0944
           initial_position: [3.25,5.6292]
           radius: 0.3
           mass: 75
           goal_weight: 2.0
           obstacle_weight: 10.0
           social_weight: 15.0
           group_gaze_weight: 0.0
           group_coh_weight: 0.0
           group_rep_weight: 0.0
           velocity: 0.9
           animation_factor: 5.1
           animation_name: "walking"
           people_distance: 6.0
           ignore_obstacles: ["circular_workspace"]
           publish_forces: False
       agent2:
           waypoints: [3.25,-5.6292,-3.25,5.6292]
           initial_orientation: -1.0472
           initial_position: [-3.25,5.6292]
           radius: 0.3
           mass: 75
           goal_weight: 2.0
           obstacle_weight: 10.0
           social_weight: 15.0
           group_gaze_weight: 0.0
           group_coh_weight: 0.0
           group_rep_weight: 0.0
           velocity: 0.9
           animation_factor: 5.1
           animation_name: "walking"
           people_distance: 6.0
           ignore_obstacles: ["circular_workspace"]
           publish_forces: False
       agent3:
           waypoints: [6.5,-0.0,-6.5,0.0]
           initial_orientation: 0.0
           initial_position: [-6.5,0.0]
           radius: 0.3
           mass: 75
           goal_weight: 2.0
           obstacle_weight: 10.0
           social_weight: 15.0
           group_gaze_weight: 0.0
           group_coh_weight: 0.0
           group_rep_weight: 0.0
           velocity: 0.9
           animation_factor: 5.1
           animation_name: "walking"
           people_distance: 6.0
           ignore_obstacles: ["circular_workspace"]
           publish_forces: False
       agent4:
           waypoints: [3.25,5.6292,-3.25,-5.6292]
           initial_orientation: 1.0472
           initial_position: [-3.25,-5.6292]
           radius: 0.3
           mass: 75
           goal_weight: 2.0
           obstacle_weight: 10.0
           social_weight: 15.0
           group_gaze_weight: 0.0
           group_coh_weight: 0.0
           group_rep_weight: 0.0
           velocity: 0.9
           animation_factor: 5.1
           animation_name: "walking"
           people_distance: 6.0
           ignore_obstacles: ["circular_workspace"]
           publish_forces: False
       agent5:
           waypoints: [-3.25,5.6292,3.25,-5.6292]
           initial_orientation: 2.0944
           initial_position: [3.25,-5.6292]
           radius: 0.3
           mass: 75
           goal_weight: 2.0
           obstacle_weight: 10.0
           social_weight: 15.0
           group_gaze_weight: 0.0
           group_coh_weight: 0.0
           group_rep_weight: 0.0
           velocity: 0.9
           animation_factor: 5.1
           animation_name: "walking"
           people_distance: 6.0
           ignore_obstacles: ["circular_workspace"]
           publish_forces: False
