agent_params_loader:
   ros__parameters:
       sampling_time: 0.033
       runge_kutta_45: True
       ground_height: -0.1
       robot_control: True
       robot_name: "pioneer3at"
       laser_sensor_name: "laser"
       robot_radius: 0.3
       robot_mass: 35
       robot_velocity: 0.9
       robot_relaxation_time: 0.5
       robot_k_orthogonal: 1.0
       robot_k_damping: 500.0
       robot_k_lambda: 0.3
       robot_alpha: 3.0
       robot_Ai: 2000.0
       robot_Aw: 2000.0
       robot_Bi: 0.08
       robot_Bw: 0.08
       robot_k1: 120000.0
       robot_k2: 240000.0
       robot_initial_orientation: -180.0
       robot_waypoints: [-6.5,-0.0,6.5,0.0]
       robot_initial_position: [6.5,0.0]
       robot_ignore_obstacles: ["circular_workspace"]
       attach_cylinder_to_humans: True
       consider_robot: True
       agents: ["agent1","agent2","agent3","agent4","agent5","agent6","agent7","agent8","agent9","agent10","agent11","agent12","agent13","agent14"]
       agent1:
           waypoints: [6.4326,0.9336,-6.4326,-0.9336]
           initial_orientation: 8.2576
           initial_position: [-6.4326,-0.9336]
           radius: 0.3
           mass: 75
           relaxation_time: 0.5
           k_orthogonal: 1.0
           k_damping: 500.0
           k_lambda: 0.3
           alpha: 3.0
           group_distance_forward: 2.0
           group_distance_orthogonal: 1.0
           k1g: 200.0
           k2g: 200.0
           Ai: 2000.0
           Aw: 2000.0
           Bi: 0.08
           Bw: 0.08
           k1: 120000.0
           k2: 240000.0
           velocity: 0.9
           animation_factor: 5.1
           animation_name: "walking"
           people_distance: 6.0
           ignore_obstacles: ["circular_workspace"]
           publish_forces: False
       agent2:
           waypoints: [1.8359,-6.2353,-1.8359,6.2353]
           initial_orientation: -73.5936
           initial_position: [-1.8359,6.2353]
           radius: 0.3
           mass: 75
           relaxation_time: 0.5
           k_orthogonal: 1.0
           k_damping: 500.0
           k_lambda: 0.3
           alpha: 3.0
           group_distance_forward: 2.0
           group_distance_orthogonal: 1.0
           k1g: 200.0
           k2g: 200.0
           Ai: 2000.0
           Aw: 2000.0
           Bi: 0.08
           Bw: 0.08
           k1: 120000.0
           k2: 240000.0
           velocity: 0.9
           animation_factor: 5.1
           animation_name: "walking"
           people_distance: 6.0
           ignore_obstacles: ["circular_workspace"]
           publish_forces: False
       agent3:
           waypoints: [5.9156,-2.6937,-5.9156,2.6937]
           initial_orientation: -24.4829
           initial_position: [-5.9156,2.6937]
           radius: 0.3
           mass: 75
           relaxation_time: 0.5
           k_orthogonal: 1.0
           k_damping: 500.0
           k_lambda: 0.3
           alpha: 3.0
           group_distance_forward: 2.0
           group_distance_orthogonal: 1.0
           k1g: 200.0
           k2g: 200.0
           Ai: 2000.0
           Aw: 2000.0
           Bi: 0.08
           Bw: 0.08
           k1: 120000.0
           k2: 240000.0
           velocity: 0.9
           animation_factor: 5.1
           animation_name: "walking"
           people_distance: 6.0
           ignore_obstacles: ["circular_workspace"]
           publish_forces: False
       agent4:
           waypoints: [-6.2411,1.8162,6.2411,-1.8162]
           initial_orientation: 163.7747
           initial_position: [6.2411,-1.8162]
           radius: 0.3
           mass: 75
           relaxation_time: 0.5
           k_orthogonal: 1.0
           k_damping: 500.0
           k_lambda: 0.3
           alpha: 3.0
           group_distance_forward: 2.0
           group_distance_orthogonal: 1.0
           k1g: 200.0
           k2g: 200.0
           Ai: 2000.0
           Aw: 2000.0
           Bi: 0.08
           Bw: 0.08
           k1: 120000.0
           k2: 240000.0
           velocity: 0.9
           animation_factor: 5.1
           animation_name: "walking"
           people_distance: 6.0
           ignore_obstacles: ["circular_workspace"]
           publish_forces: False
       agent5:
           waypoints: [-3.5258,5.4607,3.5258,-5.4607]
           initial_orientation: 122.8491
           initial_position: [3.5258,-5.4607]
           radius: 0.3
           mass: 75
           relaxation_time: 0.5
           k_orthogonal: 1.0
           k_damping: 500.0
           k_lambda: 0.3
           alpha: 3.0
           group_distance_forward: 2.0
           group_distance_orthogonal: 1.0
           k1g: 200.0
           k2g: 200.0
           Ai: 2000.0
           Aw: 2000.0
           Bi: 0.08
           Bw: 0.08
           k1: 120000.0
           k2: 240000.0
           velocity: 0.9
           animation_factor: 5.1
           animation_name: "walking"
           people_distance: 6.0
           ignore_obstacles: ["circular_workspace"]
           publish_forces: False
       agent6:
           waypoints: [3.505,5.474,-3.505,-5.474]
           initial_orientation: 57.3682
           initial_position: [-3.505,-5.474]
           radius: 0.3
           mass: 75
           relaxation_time: 0.5
           k_orthogonal: 1.0
           k_damping: 500.0
           k_lambda: 0.3
           alpha: 3.0
           group_distance_forward: 2.0
           group_distance_orthogonal: 1.0
           k1g: 200.0
           k2g: 200.0
           Ai: 2000.0
           Aw: 2000.0
           Bi: 0.08
           Bw: 0.08
           k1: 120000.0
           k2: 240000.0
           velocity: 0.9
           animation_factor: 5.1
           animation_name: "walking"
           people_distance: 6.0
           ignore_obstacles: ["circular_workspace"]
           publish_forces: False
       agent7:
           waypoints: [-6.2365,-1.832,6.2365,1.832]
           initial_orientation: -163.6298
           initial_position: [6.2365,1.832]
           radius: 0.3
           mass: 75
           relaxation_time: 0.5
           k_orthogonal: 1.0
           k_damping: 500.0
           k_lambda: 0.3
           alpha: 3.0
           group_distance_forward: 2.0
           group_distance_orthogonal: 1.0
           k1g: 200.0
           k2g: 200.0
           Ai: 2000.0
           Aw: 2000.0
           Bi: 0.08
           Bw: 0.08
           k1: 120000.0
           k2: 240000.0
           velocity: 0.9
           animation_factor: 5.1
           animation_name: "walking"
           people_distance: 6.0
           ignore_obstacles: ["circular_workspace"]
           publish_forces: False
       agent8:
           waypoints: [-4.9219,4.2456,4.9219,-4.2456]
           initial_orientation: 139.2193
           initial_position: [4.9219,-4.2456]
           radius: 0.3
           mass: 75
           relaxation_time: 0.5
           k_orthogonal: 1.0
           k_damping: 500.0
           k_lambda: 0.3
           alpha: 3.0
           group_distance_forward: 2.0
           group_distance_orthogonal: 1.0
           k1g: 200.0
           k2g: 200.0
           Ai: 2000.0
           Aw: 2000.0
           Bi: 0.08
           Bw: 0.08
           k1: 120000.0
           k2: 240000.0
           velocity: 0.9
           animation_factor: 5.1
           animation_name: "walking"
           people_distance: 6.0
           ignore_obstacles: ["circular_workspace"]
           publish_forces: False
       agent9:
           waypoints: [6.435,-0.9173,-6.435,0.9173]
           initial_orientation: -8.1127
           initial_position: [-6.435,0.9173]
           radius: 0.3
           mass: 75
           relaxation_time: 0.5
           k_orthogonal: 1.0
           k_damping: 500.0
           k_lambda: 0.3
           alpha: 3.0
           group_distance_forward: 2.0
           group_distance_orthogonal: 1.0
           k1g: 200.0
           k2g: 200.0
           Ai: 2000.0
           Aw: 2000.0
           Bi: 0.08
           Bw: 0.08
           k1: 120000.0
           k2: 240000.0
           velocity: 0.9
           animation_factor: 5.1
           animation_name: "walking"
           people_distance: 6.0
           ignore_obstacles: ["circular_workspace"]
           publish_forces: False
       agent10:
           waypoints: [-0.9376,6.432,0.9376,-6.432]
           initial_orientation: 98.2938
           initial_position: [0.9376,-6.432]
           radius: 0.3
           mass: 75
           relaxation_time: 0.5
           k_orthogonal: 1.0
           k_damping: 500.0
           k_lambda: 0.3
           alpha: 3.0
           group_distance_forward: 2.0
           group_distance_orthogonal: 1.0
           k1g: 200.0
           k2g: 200.0
           Ai: 2000.0
           Aw: 2000.0
           Bi: 0.08
           Bw: 0.08
           k1: 120000.0
           k2: 240000.0
           velocity: 0.9
           animation_factor: 5.1
           animation_name: "walking"
           people_distance: 6.0
           ignore_obstacles: ["circular_workspace"]
           publish_forces: False
       agent11:
           waypoints: [4.9165,-4.2518,-4.9165,4.2518]
           initial_orientation: -40.8531
           initial_position: [-4.9165,4.2518]
           radius: 0.3
           mass: 75
           relaxation_time: 0.5
           k_orthogonal: 1.0
           k_damping: 500.0
           k_lambda: 0.3
           alpha: 3.0
           group_distance_forward: 2.0
           group_distance_orthogonal: 1.0
           k1g: 200.0
           k2g: 200.0
           Ai: 2000.0
           Aw: 2000.0
           Bi: 0.08
           Bw: 0.08
           k1: 120000.0
           k2: 240000.0
           velocity: 0.9
           animation_factor: 5.1
           animation_name: "walking"
           people_distance: 6.0
           ignore_obstacles: ["circular_workspace"]
           publish_forces: False
       agent12:
           waypoints: [-2.7124,5.907,2.7124,-5.907]
           initial_orientation: 114.664
           initial_position: [2.7124,-5.907]
           radius: 0.3
           mass: 75
           relaxation_time: 0.5
           k_orthogonal: 1.0
           k_damping: 500.0
           k_lambda: 0.3
           alpha: 3.0
           group_distance_forward: 2.0
           group_distance_orthogonal: 1.0
           k1g: 200.0
           k2g: 200.0
           Ai: 2000.0
           Aw: 2000.0
           Bi: 0.08
           Bw: 0.08
           k1: 120000.0
           k2: 240000.0
           velocity: 0.9
           animation_factor: 5.1
           animation_name: "walking"
           people_distance: 6.0
           ignore_obstacles: ["circular_workspace"]
           publish_forces: False
       agent13:
           waypoints: [5.9087,2.7087,-5.9087,-2.7087]
           initial_orientation: 24.6278
           initial_position: [-5.9087,-2.7087]
           radius: 0.3
           mass: 75
           relaxation_time: 0.5
           k_orthogonal: 1.0
           k_damping: 500.0
           k_lambda: 0.3
           alpha: 3.0
           group_distance_forward: 2.0
           group_distance_orthogonal: 1.0
           k1g: 200.0
           k2g: 200.0
           Ai: 2000.0
           Aw: 2000.0
           Bi: 0.08
           Bw: 0.08
           k1: 120000.0
           k2: 240000.0
           velocity: 0.9
           animation_factor: 5.1
           animation_name: "walking"
           people_distance: 6.0
           ignore_obstacles: ["circular_workspace"]
           publish_forces: False
       agent14:
           waypoints: [-1.8438,6.233,1.8438,-6.233]
           initial_orientation: 106.4789
           initial_position: [1.8438,-6.233]
           radius: 0.3
           mass: 75
           relaxation_time: 0.5
           k_orthogonal: 1.0
           k_damping: 500.0
           k_lambda: 0.3
           alpha: 3.0
           group_distance_forward: 2.0
           group_distance_orthogonal: 1.0
           k1g: 200.0
           k2g: 200.0
           Ai: 2000.0
           Aw: 2000.0
           Bi: 0.08
           Bw: 0.08
           k1: 120000.0
           k2: 240000.0
           velocity: 0.9
           animation_factor: 5.1
           animation_name: "walking"
           people_distance: 6.0
           ignore_obstacles: ["circular_workspace"]
           publish_forces: False
