agent_params_loader:
  ros__parameters:
    # GLOBAL PARAMETERS
    sampling_time: 0.001
    runge_kutta_45: True
    ground_height: -0.1
    robot_control: True 
    robot_name: "pioneer3at"
    laser_sensor_name: "laser" 
    robot_initial_orientation: -90.0
    robot_waypoints: [-0.2,-7.5,-0.2,7.5]
    robot_initial_position: [-0.2,10.0]
    robot_velocity: 1.0
    robot_radius: 0.35
    robot_mass: 35
    robot_relaxation_time: 0.5
    robot_k_orthogonal: 1.0
    robot_k_damping: 500.0
    robot_k_lambda: 0.3
    robot_alpha: 3.0
    robot_Ai: 2000.0
    robot_Aw: 2000.0
    robot_Bi: 0.08
    robot_Bw: 0.08
    robot_Ci: 500.0
    robot_Cw: 500.0
    robot_Di: 0.1
    robot_Dw: 0.1
    robot_k1: 120000.0
    robot_k2: 240000.0
    robot_ignore_obstacles: [""]
    agents: ["agent1","agent2"] 
    attach_cylinder_to_humans: True
    consider_robot: True 
    # ACTORS PARAMETERS
    agent1:
      waypoints: [-2.0,1.25,-2.0,-1.25,-0.2,-5.0,-0.2,5.0]
      initial_orientation: -90.0
      initial_position: [-0.2,5.0] 
      velocity: 0.9
      radius: 0.35
      mass: 75
      relaxation_time: 0.5
      k_orthogonal: 1.0
      k_damping: 500.0
      k_lambda: 0.3
      alpha: 3.0
      group_distance_forward: 2.0
      group_distance_orthogonal: 1.0
      k1g: 200.0
      k2g: 200.0
      Ai: 2000.0
      Aw: 2000.0
      Bi: 0.08
      Bw: 0.08
      Ci: 500.0
      Cw: 500.0
      Di: 0.1
      Dw: 0.1
      k1: 120000.0
      k2: 240000.0
      animation_factor: 5.1
      animation_name: "walking"
      ignore_obstacles: [""]
      #group: ["agent2"]
      publish_forces: False
    agent2:
      waypoints: [-0.2,5.0,-2.0,1.25,-2.0,-1.25,-0.2,-5.0]
      initial_orientation: 90.0 
      initial_position: [-0.2,-5.0]
      velocity: 0.9
      radius: 0.35
      mass: 75
      relaxation_time: 0.5
      k_orthogonal: 1.0
      k_damping: 500.0
      k_lambda: 0.3
      alpha: 3.0
      group_distance_forward: 2.0
      group_distance_orthogonal: 1.0
      k1g: 200.0
      k2g: 200.0
      Ai: 2000.0
      Aw: 2000.0
      Bi: 0.08
      Bw: 0.08
      Ci: 500.0
      Cw: 500.0
      Di: 0.1
      Dw: 0.1
      k1: 120000.0
      k2: 240000.0
      animation_factor: 5.1
      animation_name: "walking"
      ignore_obstacles: [""]
      #group: ["agent2"]
      publish_forces: False